# Generated by Django 3.2.8 on 2021-10-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
